name: Backend Continuous Integration

on:
  # trigger on every pull request against main
  pull_request:
    branches:
      - main

  # just for testing purpose
  push:
    branches:
      - main

  # the pipeline can be run manually
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      # use my customized action to setup python and dependencies and run command
      - name: Python setup and command execution
        uses: ./.github/actions/python-setup-and-execution
        with:
          python-version: 3.10
          job-command: 'lint'

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup Python latest
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: |
          cd starter/backend
          python -m pip install --upgrade pipenv

      - name: Install dependencies
        run: |
          cd starter/backend
          pipenv install --dev

      - name: Run test
        run: |
          cd starter/backend
          pipenv run test

  build:
    needs: [linting, test]
    runs-on: ubuntu-latest
        
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: |
          cd starter/backend
          docker build . --file Dockerfile --tag backend-build-image
        
      # - name: Run the Docker container
      #   run: |
      #     cd starter/backend
      #     ls
      #     docker run --rm backend-build-image
