name: Destroy infrastructure via Terraform

# the pipeline only runs manually
on: workflow_dispatch

jobs:
  # setup the infrastructure on aws
  IaaS:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: us-east-1

      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9

      - name: Terraform Initialize
        run: |
          cd setup/terraform
          terraform init

    #   - name: Terraform Validate
    #     run: |
    #       cd setup/terraform
    #       terraform validate

    #   - name: Terraform Plan
    #     run: |
    #       cd setup/terraform
    #       terraform plan
    #     continue-on-error: true

    #   - name: Terraform Apply
    #     run: |
    #       cd setup/terraform
    #       terraform apply -auto-approve

      - name: Terraform Destroy
        run: |
          cd setup/terraform
          terraform destroy -auto-aaprove ./setup/terraform
