name: Frontend Continuous Integration

on:
  # trigger on every pull request against main
  pull_request:
    branches:
      - main

  # just for testing purpose
  push:
    branches:
      - main

  # the pipeline can be run manually
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: List contents of the actions directory
        run: ls -R ./.github/actions/

      - name: Node.js setup
        uses: ./.github/actions/node-ci-setup
        with:
          node-version: lts/*
