name: Frontend Continuous Integration

on:
  # trigger on every pull request against main
  pull_request:
    branches:
      - main

  # just for testing purpose
  # push:
  #   branches:
  #     - main

  # the pipeline can be run manually
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      # checkout repository first
      - name: Checkout repository
        uses: actions/checkout@v2

     # for debugging purpose
      # - name: List contents of the actions directory
      #   run: ls -R ./.github/actions/

      # use my customized action to setup node and dependencies and run command
      - name: Node.js setup
        uses: ./.github/actions/node-setup-and-execution
        with:
          node-version: lts/*
          path-to-workdir: 'starter/frontend'
          job-command: 'lint'
  
  # test job
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      # use my customized action to setup node and dependencies and run command
      - name: Node.js setup
        uses: ./.github/actions/node-setup-and-execution
        with:
          node-version: lts/*
          path-to-workdir: 'starter/frontend'
          job-command: 'test'

  # build job
  build:
    needs: [linting, test]
    runs-on: ubuntu-latest
        
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      # use my customized action to setup node and dependencies and run command
      - name: Node.js setup
        uses: ./.github/actions/node-setup-and-execution
        with:
          node-version: lts/*
          path-to-workdir: 'starter/frontend'
          job-command: 'build'
